name: Build and Deploy Flask App

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Enable manual trigger
  schedule:
    - cron: "0 11 * * 1-5"  # Runs at 11 AM UTC (4 PM IST) from Monday to Friday

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        architecture: 'x64'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        mkdir -p static/images

    - name: Freeze Flask app
      run: |
        python app.py freeze

    - name: Clone MarketInsights repository
      run: |
        git clone https://github.com/Anshuman2121/MarketInsights.git

    - name: Copy index.html to MarketInsights repository
      run: |
        mv build/index.html MarketInsights/index.html
        mv build/midcap100 MarketInsights/midcap100.html
        mv build/niftynext50 MarketInsights/niftynext50.html
        sed -i '' 's,/static/images/,static/images/,g' build/chart
        sed -i '' 's,/static/images/,static/images/,g' build/chartindex
        mv build/chart MarketInsights/chart.html
        mv build/chartindex MarketInsights/chartindex.html
        rm -rf MarketInsights/static/images/*
        cp -rf build/static/images/* MarketInsights/static/images/

    - name: Configure Git
      run: |
        git config --global user.email "anshuman2121@gmail.com"
        git config --global user.name "Anshuman2121"

    - name: Push changes to MarketInsights repository
      env:
        USERNAME: ${{ secrets.USERNAME }}
        TOKEN: ${{ secrets.TOKEN }}
      run: |
        cd MarketInsights
        git remote set-url origin https://$USERNAME:$TOKEN@github.com/Anshuman2121/MarketInsights.git
        git add .
        git commit -m "Update index.html"
        git push origin main
