name: Build and Deploy Flask App

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Enable manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Freeze Flask app
      run: |
        python app.py freeze

    - name: Clone stockprediction_pages repository
      run: |
        git clone https://github.com/Anshuman2121/stockprediction_pages.git

    - name: Copy index.html to stockprediction_pages repository
      run: |
        mv build/index.html stockprediction_pages/index.html

    - name: Configure Git
      run: |
        git config --global user.email "anshuman2121@gmail.com"
        git config --global user.name "Anshuman2121"

    - name: Push changes to stockprediction_pages repository
      env:
        USERNAME: ${{ secrets.USERNAME }}
        TOKEN: ${{ secrets.TOKEN }}
      run: |
        cd stockprediction_pages
        git remote set-url origin https://$USERNAME:$TOKEN@github.com/Anshuman2121/stockprediction_pages.git
        git add index.html
        git commit -m "Update index.html"
        git push origin main
