name: Build and Deploy Flask App

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Enable manual trigger
  schedule:
    - cron: "0 11 * * 1-5"  # Runs at 11 AM UTC (4 PM IST) from Monday to Friday

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Freeze Flask app
      run: |
        python app.py freeze

    - name: Clone MarketInsights repository
      run: |
        git clone https://github.com/Anshuman2121/MarketInsights.git

    - name: Copy index.html to MarketInsights repository
      run: |
        mv build/index.html MarketInsights/index.html

    - name: Configure Git
      run: |
        git config --global user.email "anshuman2121@gmail.com"
        git config --global user.name "Anshuman2121"

    - name: Push changes to MarketInsights repository
      env:
        USERNAME: ${{ secrets.USERNAME }}
        TOKEN: ${{ secrets.TOKEN }}
      run: |
        cd MarketInsights
        git remote set-url origin https://$USERNAME:$TOKEN@github.com/Anshuman2121/MarketInsights.git
        git add index.html
        git commit -m "Update index.html"
        git push origin main
